// Code generated by MockGen. DO NOT EDIT.
// Source: delete_banner.go

// Package mock_deletebanner is a generated GoMock package.
package mock_deletebanner

import (
	reflect "reflect"

	banner "github.com/CyberPiess/banner_sevice/internal/domain/banner"
	gomock "github.com/golang/mock/gomock"
)

// MockdeleteBannerService is a mock of deleteBannerService interface.
type MockdeleteBannerService struct {
	ctrl     *gomock.Controller
	recorder *MockdeleteBannerServiceMockRecorder
}

// MockdeleteBannerServiceMockRecorder is the mock recorder for MockdeleteBannerService.
type MockdeleteBannerServiceMockRecorder struct {
	mock *MockdeleteBannerService
}

// NewMockdeleteBannerService creates a new mock instance.
func NewMockdeleteBannerService(ctrl *gomock.Controller) *MockdeleteBannerService {
	mock := &MockdeleteBannerService{ctrl: ctrl}
	mock.recorder = &MockdeleteBannerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeleteBannerService) EXPECT() *MockdeleteBannerServiceMockRecorder {
	return m.recorder
}

// DeleteBanner mocks base method.
func (m *MockdeleteBannerService) DeleteBanner(newPutBanner banner.BannerEntity, user banner.User) (bool, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBanner", newPutBanner, user)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteBanner indicates an expected call of DeleteBanner.
func (mr *MockdeleteBannerServiceMockRecorder) DeleteBanner(newPutBanner, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBanner", reflect.TypeOf((*MockdeleteBannerService)(nil).DeleteBanner), newPutBanner, user)
}

// PostBanner mocks base method.
func (m *MockdeleteBannerService) PostBanner(newPostBanner banner.BannerEntity, user banner.User) (int, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostBanner", newPostBanner, user)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PostBanner indicates an expected call of PostBanner.
func (mr *MockdeleteBannerServiceMockRecorder) PostBanner(newPostBanner, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostBanner", reflect.TypeOf((*MockdeleteBannerService)(nil).PostBanner), newPostBanner, user)
}

// PutBanner mocks base method.
func (m *MockdeleteBannerService) PutBanner(newPutBanner banner.BannerEntity, user banner.User) (bool, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutBanner", newPutBanner, user)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PutBanner indicates an expected call of PutBanner.
func (mr *MockdeleteBannerServiceMockRecorder) PutBanner(newPutBanner, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutBanner", reflect.TypeOf((*MockdeleteBannerService)(nil).PutBanner), newPutBanner, user)
}

// SearchAllBanners mocks base method.
func (m *MockdeleteBannerService) SearchAllBanners(bannerFilter banner.GetAllFilter, user banner.User) ([]banner.BannerEntity, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAllBanners", bannerFilter, user)
	ret0, _ := ret[0].([]banner.BannerEntity)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchAllBanners indicates an expected call of SearchAllBanners.
func (mr *MockdeleteBannerServiceMockRecorder) SearchAllBanners(bannerFilter, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAllBanners", reflect.TypeOf((*MockdeleteBannerService)(nil).SearchAllBanners), bannerFilter, user)
}

// SearchBanner mocks base method.
func (m *MockdeleteBannerService) SearchBanner(bannerFilter banner.GetFilter, user banner.User) (banner.BannerEntity, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchBanner", bannerFilter, user)
	ret0, _ := ret[0].(banner.BannerEntity)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchBanner indicates an expected call of SearchBanner.
func (mr *MockdeleteBannerServiceMockRecorder) SearchBanner(bannerFilter, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchBanner", reflect.TypeOf((*MockdeleteBannerService)(nil).SearchBanner), bannerFilter, user)
}
