// Code generated by MockGen. DO NOT EDIT.
// Source: user_banner.go

// Package mock_userbanner is a generated GoMock package.
package mock_userbanner

import (
	reflect "reflect"

	banner "github.com/CyberPiess/banner_sevice/internal/domain/banner"
	gomock "github.com/golang/mock/gomock"
)

// MockbannerService is a mock of bannerService interface.
type MockbannerService struct {
	ctrl     *gomock.Controller
	recorder *MockbannerServiceMockRecorder
}

// MockbannerServiceMockRecorder is the mock recorder for MockbannerService.
type MockbannerServiceMockRecorder struct {
	mock *MockbannerService
}

// NewMockbannerService creates a new mock instance.
func NewMockbannerService(ctrl *gomock.Controller) *MockbannerService {
	mock := &MockbannerService{ctrl: ctrl}
	mock.recorder = &MockbannerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbannerService) EXPECT() *MockbannerServiceMockRecorder {
	return m.recorder
}

// SearchBanner mocks base method.
func (m *MockbannerService) SearchBanner(bannerFilter banner.Filter, user banner.User) (banner.BannerEntity, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchBanner", bannerFilter, user)
	ret0, _ := ret[0].(banner.BannerEntity)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchBanner indicates an expected call of SearchBanner.
func (mr *MockbannerServiceMockRecorder) SearchBanner(bannerFilter, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchBanner", reflect.TypeOf((*MockbannerService)(nil).SearchBanner), bannerFilter, user)
}
